on: [push]

name: AzurePowerShellSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout source code
      uses: actions/checkout@v2    

    # - name: Login via Az module
    #   uses: azure/login@v1.1
    #   with:
    #     creds: ${{secrets.AZURE_CREDENTIALS}}
    #     enable-AzPSSession: true 
    
    # - name: Run Az CLI script
    #   run: |
    #     az webapp list --query "[?state=='Running']"
   
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        azPSVersion: '3.1.0'
        inlineScript: |
          Set-AzContext ad54c4fb-f585-4033-9e5a-b119d74480b0
          # az login
          Get-AzResource -ResourceGroupName rg-action
